session_name: Config
start_directory: ~/Jetragapult/
windows:
  - window_name: root 
    layout: even-horizontal
    panes:
      - shell_command: nvim .
  - window_name: nvim
    start_directory: ~/Jetragapult/nvim/.config/nvim/
    layout: even-horizontal
    panes:
      - shell_command: nvim .
  - window_name: tmuxp
    start_directory: ~/Jetragapult/tmuxp/.config/tmuxp/
    panes:
      - shell_command: nvim .
  - window_name: fish
    start_directory: ~/Jetragapult/fish/.config/fish/
    panes:
      - shell_command: nvim .


