[opener]
edit = [
    { run = 'nvim "$@"', block = true, desc = "Neovim", for = "unix" }
]
edit_dir = [
    { run = 'cd "%s1" && nvim .', block = true, desc = "Neovim in directory", for = "unix" }
]

[open]
prepend_rules = [
	{ mime = "folder/*", use = "edit_dir" },
	{ url = "*/", use = "edit_dir" },
	{ url = "*.json", use = "edit" },

	# Multiple openers for a single rule
	{ url = "*.html", use = [ "open", "edit" ] },
]
append_rules = [
	{ url = "*", use = "edit" },
]

[manager]
sort_by = "natural"
